# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MM=/usr/bin/gcc
MXX=/usr/bin/g++
CC=/usr/bin/gcc
CXX=/usr/bin/g++
AS=/usr/bin/gcc

AR=/usr/bin/ar
LD=/usr/bin/g++
SH=/usr/bin/g++

my_jieba_demo_LD=/usr/bin/g++
my_jieba_demo_CXX=/usr/bin/g++
my_jieba_demo_CXX=/usr/bin/g++
my_jieba_demo_CXX=/usr/bin/g++

my_jieba_demo_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -isystem /home/ubuntu/.xmake/packages/c/cppjieba/@default/725e51fe81b74141ade9efbd3ccaf900/include -DNDEBUG
my_jieba_demo_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -isystem /home/ubuntu/.xmake/packages/c/cppjieba/@default/725e51fe81b74141ade9efbd3ccaf900/include -DNDEBUG
my_jieba_demo_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -isystem /home/ubuntu/.xmake/packages/c/cppjieba/@default/725e51fe81b74141ade9efbd3ccaf900/include -DNDEBUG
my_jieba_demo_LDFLAGS=-m64 -s

default:  my_jieba_demo

all:  my_jieba_demo

.PHONY: default all  my_jieba_demo

my_jieba_demo: build/linux/x86_64/release/my_jieba_demo
build/linux/x86_64/release/my_jieba_demo: build/.objs/my_jieba_demo/linux/x86_64/release/src/main.cpp.o build/.objs/my_jieba_demo/linux/x86_64/release/src/HotWordSystem.cpp.o
	@echo linking.release my_jieba_demo
	@mkdir -p build/linux/x86_64/release
	$(VV)$(my_jieba_demo_LD) -o build/linux/x86_64/release/my_jieba_demo build/.objs/my_jieba_demo/linux/x86_64/release/src/main.cpp.o build/.objs/my_jieba_demo/linux/x86_64/release/src/HotWordSystem.cpp.o $(my_jieba_demo_LDFLAGS)

build/.objs/my_jieba_demo/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo compiling.release src/main.cpp
	@mkdir -p build/.objs/my_jieba_demo/linux/x86_64/release/src
	$(VV)$(my_jieba_demo_CXX) -c $(my_jieba_demo_CXXFLAGS) -o build/.objs/my_jieba_demo/linux/x86_64/release/src/main.cpp.o src/main.cpp

build/.objs/my_jieba_demo/linux/x86_64/release/src/HotWordSystem.cpp.o: src/HotWordSystem.cpp
	@echo compiling.release src/HotWordSystem.cpp
	@mkdir -p build/.objs/my_jieba_demo/linux/x86_64/release/src
	$(VV)$(my_jieba_demo_CXX) -c $(my_jieba_demo_CXXFLAGS) -o build/.objs/my_jieba_demo/linux/x86_64/release/src/HotWordSystem.cpp.o src/HotWordSystem.cpp

clean:  clean_my_jieba_demo

clean_my_jieba_demo: 
	@rm -rf build/linux/x86_64/release/my_jieba_demo
	@rm -rf build/linux/x86_64/release/my_jieba_demo.sym
	@rm -rf build/.objs/my_jieba_demo/linux/x86_64/release/src/main.cpp.o
	@rm -rf build/.objs/my_jieba_demo/linux/x86_64/release/src/HotWordSystem.cpp.o

