add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
add_requires("cppjieba")
    
target("WaifuTopK")
    set_kind("binary")
    add_files("src/*.cpp") 
    add_packages("cppjieba")
    set_languages("c++17")
    add_includedirs("src") 
    set_rundir("$(projectdir)") 
